export const FREIGHT_UPLOAD = "FREIGHT_UPLOAD";
export const FREIGHT_RETRIEVE = "FREIGHT_RETRIEVE";
export const FREIGHT_SHAREPOINT = "FREIGHT_SHAREPOINT";
export const FREIGHT_LOADING = "FREIGHT_LOADING";
export const FREIGHT_ERROR = "FREIGHT_ERROR";
export const FREIGHT_RECONCILATION = "FREIGHT_RECONCILATION";
