export const AP_RECONCILE_TABLE = "AP_RECONCILE_TABLE";
export const AP_INVOICE_RECONCILATION = "AP_INVOICE_RECONCILATION";
export const TABLE_LOADING = "TABLE_LOADING";
export const COUNTERS = "COUNTERS";
export const ACTIVE_COUNTER = "ACTIVE_COUNTER";
export const TABLE_SEARCH = "TABLE_SEARCH";
export const EMAIL_WORKFLOW = "EMAIL_WORKFLOW";
export const EMAIL_REJECT = "EMAIL_REJECT";
